#! /bin/bash

TIMEF=.test_time_file

trap "rm -f $TIMEF" EXIT

for di in {1..25}; do
  d=day"$di"
  luafile="$d".lua
  if [ -e "$luafile" ]; then
    for i in 1 2; do
      printf "%s\tpart%d: " "$d" "$i"
      if diff -w "io/$d/part${i}.txt" <((time -p lua "$luafile" ${i} < "io/$d/input.txt") 2>$TIMEF) &> /dev/null; then
        echo -ne $'\e[32m+\e[0m'
      else
        echo -ne $'\e[31m-\e[0m'
      fi
      elapsed=$(head -1 "$TIMEF" | awk '{ print $2; }')
      printf " (%ss)\n" "$elapsed"
    done
  fi
done
